# Generated by Django 4.0 on 2022-01-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClgsCutoffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_code', models.CharField(max_length=10)),
                ('inst_name', models.CharField(max_length=100)),
                ('own_type', models.CharField(choices=[('PVT', 'PRIVATE'), ('SF', 'SELF FUNDED'), ('UNIV', 'UNIVERSITY')], max_length=5)),
                ('reg_type', models.CharField(max_length=5)),
                ('dist', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=100)),
                ('coed_type', models.CharField(max_length=10)),
                ('affliated_univ', models.CharField(max_length=100)),
                ('estd_year', models.CharField(max_length=50)),
                ('branch_code', models.CharField(max_length=50)),
                ('oc_boys_cr', models.CharField(max_length=50)),
                ('oc_girls_cr', models.CharField(max_length=50)),
                ('sc_boys_cr', models.CharField(max_length=50)),
                ('sc_girls_cr', models.CharField(max_length=50)),
                ('st_boys_cr', models.CharField(max_length=50)),
                ('st_girls_cr', models.CharField(max_length=50)),
                ('bca_boys_cr', models.CharField(max_length=50)),
                ('bca_girls_cr', models.CharField(max_length=50)),
                ('bcb_boys_cr', models.CharField(max_length=50)),
                ('bcb_girls_cr', models.CharField(max_length=50)),
                ('bcc_boys_cr', models.CharField(max_length=50)),
                ('bcc_girls_cr', models.CharField(max_length=50)),
                ('bcd_boys_cr', models.CharField(max_length=50)),
                ('bcd_girls_cr', models.CharField(max_length=50)),
                ('bce_boys_cr', models.CharField(max_length=50)),
                ('bce_girls_cr', models.CharField(max_length=50)),
                ('oc_ews_boys_cr', models.CharField(max_length=50)),
                ('oc_ews_girls_cr', models.CharField(max_length=50)),
                ('college_fee', models.CharField(max_length=50)),
            ],
        ),
    ]
