# Generated by Django 4.0 on 2022-01-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapcet_clgpredictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bca_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bca_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bcb_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bcb_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bcc_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bcc_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bcd_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bcd_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bce_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='bce_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='college_fee',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='oc_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='oc_ews_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='oc_ews_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='oc_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='sc_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='sc_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='st_boys_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='clgscutoffs',
            name='st_girls_cr',
            field=models.PositiveIntegerField(default=-1),
        ),
    ]
